### ISSUE TITLE
Add the avatar image to the vcard

### ISSUE THREAD

**Issue by kirkone** [kirkone/Snappy.Cards#10]
maybe something like this will work:

```csharp
// Add image
builder.AppendLine("PHOTO;ENCODING=BASE64;TYPE=JPEG:");
builder.AppendLine(Convert.ToBase64String(Image));
builder.AppendLine(string.Empty);
```

**Comment by Satvik-web** [comment]
if you are using C#.. There is an awesome nuget package called VCard which helps you to create VCards easily..
You can just give the image url and it will give you the proper VCard with the image in it..
Here is the link for the package..

Link : https://www.nuget.org/packages/VCard/

Or you can search for Card in VS manage nuget packages tab and install the package in the 3rd result..

**Comment by kirkone** [comment]
Hi @Satvik-web,

I saw your package and got the idea from there. Unfortunately, here we are using plain JavaScript to generate the vcard.
So, this might not work in our case.

**Comment by Satvik-web** [comment]
Thank a lot @kirkone for checking out my package..
I actually thought you were using C#.. I wish GitHub has an option to specify the language..
Anyway, nice to see you..

**Comment by kirkone** [comment]
> I wish GitHub has an option to specify the language.

at least there is this one the start page:
See at the bottom right.
![image](https://user-images.githubusercontent.com/15778270/152109344-fbf4c3aa-aa4c-4d2d-a9d8-cb49e8ce38fb.png)
